### ISSUE TITLE
setTime() declaration error between Rtc_Pcf8563.h and Rtc_Pcf8563.cpp

### ISSUE THREAD

**Issue by DeonBarnard** [orbitalair/Rtc_Pcf8563#2]
Hi

Still a little new to GitHub so just reporting this here. I have found a skew between the Rtc_Pcf8563.h and Rtc_Pcf8563.cpp files with the function setTime().

The parameter orders (h, m, s) are swapped between the .h and .cpp files which causes an error when hours (seconds) are more  than 23 (besides always giving the wrong time).

Thanks

**Comment by orbitalair** [comment]
Merge fix.  apologies for taking so long, I havent been on arduino for ages.
